title: SlowStepsFI
email: slowsteps18@gmail.com
description: Slow Steps Towards Finance Independance
author: Mike
baseurl: "/"
url: "https://slowstepsfi.com"

# Add your google-analytics ID here to activate google analytics
google_analytics: G-G8BGX8HERN

# Build settings
markdown: kramdown
paginate: 10
paginate_path: "/articles/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
